"""Label aliases and patterns used to identify Bangladesh NID fields."""

FIELD_LABELS = {
    "name": ["name", "নাম", "নামঃ"],
    "fatherName": ["father's name", "father name", "father", "পিতার নাম", "পিতা"],
    "motherName": ["mother's name", "mother name", "mother", "মাতার নাম", "মাতা"],
    "dateOfBirth": ["date of birth", "dob", "birth", "জন্ম তারিখ"],
    "nidNumber": [
        "nid no",
        "nid number",
        "nid",
        "id no",
        "id number",
        "জাতীয় পরিচয় নম্বর",
        "জাতীয় পরিচয় নম্বর",
    ],
    "presentAddress": ["present address", "বর্তমান ঠিকানা", "present add"],
    "permanentAddress": ["permanent address", "স্থায়ী ঠিকানা", "স্থায়ী ঠিকানা"],
}

ADDRESS_TERMS = [
    "গ্রাম",
    "বাসা",
    "বাড়ি",
    "বাড়ি",
    "রোড",
    "ডাকঘর",
    "থানা",
    "উপজেলা",
    "জেলা",
    "ওয়ার্ড",
    "ওয়ার্ড",
    "ইউনিয়ন",
    "ইউনিয়ন",
    "বিভাগ",
    "পোঃ",
    "পো",
]

TRANSLITERATION_EXCEPTIONS = {
    "মোঃ": "Md.",
    "মো:": "Md.",
    "মো.": "Md.",
    "মো": "Md.",
    "মোহঃ": "Md.",
    "আব্দুল": "Abdul",
    "রহিম": "Rahim",
    "করিম": "Karim",
    "বেগম": "Begum",
    "হোসেন": "Hossain",
    "হাসান": "Hasan",
    "আলী": "Ali",
    "ঢাকা": "Dhaka",
    "কুমিল্লা": "Cumilla",
    "চট্টগ্রাম": "Chattogram",
    "সিলেট": "Sylhet",
    "রংপুর": "Rangpur",
    "খুলনা": "Khulna",
    "বরিশাল": "Barishal",
    "রাজশাহী": "Rajshahi",
    "ময়মনসিংহ": "Mymensingh",
    "ময়মনসিংহ": "Mymensingh",
    "গাজীপুর": "Gazipur",
    "নারায়ণগঞ্জ": "Narayanganj",
    "নারায়ণগঞ্জ": "Narayanganj",
    "বাংলাদেশ": "Bangladesh",
    "গ্রাম": "Village",
    "বাসা": "House",
    "বাড়ি": "House",
    "বাড়ি": "House",
    "রোড": "Road",
    "ডাকঘর": "Post Office",
    "থানা": "Thana",
    "উপজেলা": "Upazila",
    "জেলা": "District",
    "ওয়ার্ড": "Ward",
    "ওয়ার্ড": "Ward",
    "ইউনিয়ন": "Union",
    "ইউনিয়ন": "Union",
    "বিভাগ": "Division",
    "পোঃ": "PO",
    "পো": "PO",
}
